server:
  port: 8080
  contextPath: /vim-maven
spring:
  profiles: local, default, prod
datasource:
  vim:
    url: jdbc:mysql://localhost:3306/vim?useSSL=false
    username: root
    password: root
    driverClassName: com.mysql.jdbc.Driver
    hibernate:
      hbm2ddl.method: update
      show_sql: true
      format_sql: true
      dialect: org.hibernate.dialect.MySQLDialect

